<?php $form->setAttribute('action', '/pacientes/nuevo');?>
<?php $form->setAttribute('class', 'hva-form');?>
<?php $form->prepare();?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col s3">
        <div class="input-field">
            <?php echo $this->formText($form->get('cita_fecha')); ?>
            <?php echo $this->formLabel($form->get('cita_fecha')); ?>
        </div>
    </div>
    <div class="col s3">
        <div class="input-field">
            <?php echo $this->formText($form->get('cita_hora')); ?>
            <?php echo $this->formLabel($form->get('cita_hora')); ?>
        </div>
    </div>
    <div class="col s6">
        <div class="input-field">
            <?php echo $this->formSelect($form->get('idmedico')); ?>
        </div>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
        $("#fecha").datepicker();
    });
</script>