<?php
$title = $pacienteEntity->getPacienteNombre()." ".$pacienteEntity->getPacienteAp()." ".$pacienteEntity->getPacienteAm();
$this->headTitle($title);
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>
<div>
<fieldset>
    <legend>Datos generales del paciente</legend>
    <div class="col s4">
        <div class="label-container">
            <label>Fecha de nacimiento:</label>
            <p><?php echo $pacienteEntity->getPacienteFechanacimiento()?></p>
        </div>
        <div class="label-container">
            <label>Responsable:</label>
            <p><?php echo $pacienteEntity->getPacienteResponsable()?></p>
        </div>
    </div>
    <div class="col s4">
        <div class="label-container">
            <label>Edad:</label>
            <p><?php echo $edad . " años"?></p>
        </div>
        <div class="label-container">
            <label>Teléfono responsable:</label>
            <p><?php echo $pacienteEntity->getPacienteTelefonoresponsable()?></p>
        </div>
    </div>
    <div class="col s4">
        <div class="label-container">
            <label>Sexo:</label>
            <p><?php echo $pacienteEntity->getPacienteSexo()?></p>
        </div>
    </div>
</fieldset>
<br>
<div class="row">
    <fieldset>
        <legend>Para uso exclusivo del hospital</legend>
        <?php if($consultorioEnuso == 1) : ?>
            <div class="col s12">
                <div id="radioConsulta" class="col s4">
                    <input class="with-gap" name="grupo1" type="radio" id="test3" checked/>
                    <label for="test3">Consulta</label>
                </div>
            </div>
            <div class="col s4">
                <div class="label-container">
                    <label>Médico:</label>
                    <p><?php echo $consultaByPaciente->getMedico()->getMedicoNombre()?></p>
                </div>
                <div class="label-container">
                    <label>Consultorio:</label>
                    <p><?php echo $consultaByPaciente->getConsultorio()->getConsultorioNombre()?></p>
                </div>
            </div>
            <div class="col s4">
                <div class="label-container">
                    <label>Fecha de consulta:</label>
                    <p><?php echo $consultaByPaciente->getConsultaFecha()?></p>
                </div>
                <div class="label-container">
                    <label>Hora de consulta:</label>
                    <p><?php echo $consultaByPaciente->getConsultaHora()?></p>
                </div>
            </div>
            <div class="col s4">
                <div class="label-container">
                    <label>Diagnóstico:</label>
                    <p><?php echo $consultaByPaciente->getConsultaDiagnostico()?></p>
                </div>
                <div class="label-container">
                    <label>Observación:</label>
                    <p><?php echo $consultaByPaciente->getConsultaObservaciones()?></p>
                </div>
            </div>
        <?php elseif($cuartoEnuso == 1) :?>
            <div class="col s12">
                <div id="radioAdmision" class="col s4">
                    <input class="with-gap" name="grupo1" type="radio" id="test4" checked />
                    <label for="test4">Admisión</label>
                </div>
            </div>
            <div class="col s4">
                <div class="label-container">
                    <label>Médico:</label>
                    <p><?php echo $admisionByPaciente->getMedico()->getMedicoNombre()?></p>
                </div>
                <div class="label-container">
                    <label>Consultorio:</label>
                    <p><?php echo $admisionByPaciente->getCuarto()->getCuartoNombre()?></p>
                </div>
            </div>
            <div class="col s4">
                <div class="label-container">
                    <label>Fecha de admisión:</label>
                    <p><?php echo $admisionByPaciente->getAdmisionFechaadmision()?></p>
                </div>
            </div>
            <div class="col s4">
                <div class="label-container">
                    <label>Diagnóstico:</label>
                    <p><?php echo $admisionByPaciente->getAdmisionDiagnostico()?></p>
                </div>
                <div class="label-container">
                    <label>Observación:</label>
                    <p><?php echo $admisionByPaciente->getAdmisionObservaciones()?></p>
                </div>
            </div>
        <?php endif ?>
    </fieldset>
</div>
