<?php

return array(
    'Administrador' => array(
        'home',
        'auth',
        //Catalogos
        'proveedor',
        'articulo',
        'medico',
        'especialidad',
        'cuarto',
        'consultorio',
        'servicio',
        //Caja
        'cajachica-concepto',
        'cajachica-movimientos',
        'cajachica-movimientos-conceptos',
        //Bancos
        'bancos-concepto',
        'bancos-movimientos ',
        //Reportes
        'reportes-ingresos',
        'reportes-general',
        'pacientes-historico',
        //Empleados
        'empleados',
        //Almacen
        'lugar',
        'almacen-transferencias',
        //compras
        'compras',
        //Productos
        'productos-producto',
        'productos-precios',
        'productos-reorden',
        'productos-registro',
        'productos-existencias',
        'productos-existencias',
        'productos-existencias/productos-existencias-caducidadbylugar',
        'productos-reorden/productos-reorden-definir',
        //pacientes
        'pacientes',
        'cargoconsulta',
        'consultaanticipo',
        'pacientes-historico',
        'pacientes-historicos',
        'citas-agendar',
        'citas',
        'admisionanticipo',
        //venta
        'venta',
        //facturacion
        'facturacion-facturar',
        'facturacion-emitidas',
        'facturacion-canceladas'
    ),
    'Caja' => array(
        'auth',
        'home',
        //Caja
        'cajachica-concepto',
        'cajachica-movimientos',
        'cajachica-movimientos-conceptos',
        //Productos
        'productos-precios',
        'productos-existencias',
        //pacientes
        'pacientes',
        'cargoconsulta',
        'consultaanticipo',
        'pacientes-historicos',
        'citas-agendar',
        'citas',
        'admisionanticipo',
        //venta
        'venta',
        //facturacion
        'facturacion-facturar',
    ),
    'Enfermeria' => array(
        'auth',
        'home',
        //Almacen
        'almacen-transferencias',
        //compras
        'productos-producto',
        //pacientes
        'cargoconsulta',
        //venta
        'venta',
    ),
    'Admision' => array(
        'auth',
        'home',
        //pacientes
        'pacientes',
        'citas-agendar',
        'citas',
    ),
    'Quirofano' => array(
        'auth',
        'home',
        //Almacen
        'almacen-transferencias',
    ),
    'Farmacia' => array(
        'auth',
        'home',
        //Almacen
        'almacen-transferencias',
        //venta
        'venta',
    ),
    'Almacen' => array(
        'auth',
        'home',
        //Almacen
        'almacen-transferencias',
        //Productos
        'productos-existencias',
        'productos-reorden',
    ),
);
