<?php
$title = 'Historico de pacientes';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <div class="col s12"> 
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </div>
</div>
    <table id="tabla-paciente" class="bordered">
        <thead>
        <tr>
            <th>Fecha</th>
            <th>Hora</th>
            <th># Movimiento</th>
            <th>Paciente</th>
            <th>Medico</th>
            <th>Tipo</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($collection as $entity) :?>
            <tr>
                <td><?php echo $entity['fecha']?></td>
                <td><?php echo $entity['hora']?></td>
                <td><?php echo $entity['id']?></td>
                <td><?php echo $entity['paciente']?></td>
                <td><?php echo $entity['medico']?></td>
                <td><?php echo $entity['tipo']?></td>
            </tr>  
        <?php endforeach; ?>
        </tbody>
    </table>
<script type="text/javascript">
    $(document).ready(function(){

        $("#tabla-paciente").tablesorter();
        $("#tabla-paciente").filterTable({inputSelector: '#search-container input',minRows:1});
    });
</script>