<style>
    
    table.ui-datepicker-calendar {
        //display: none;
    }
    
    .ui-datepicker .ui-datepicker-title select{
        display: inline-block;
    }
    
    div#ui-datepicker-div{
        padding: 0;
        border: 0;
    }
    
    .ui-datepicker .ui-datepicker-prev, .ui-datepicker .ui-datepicker-next{
        //display: none;
    }
    
    .ui-widget-header{
/*        background: #E1F5FE;
        border: solid 1px #405C95;
        color: #405C95;*/
    }
    
    .ui-datepicker-title select{
        //height: 30px;
    }
    
</style>
<?php
    $title = 'Factura #'.$orden['nofactura'];
    $this->headTitle($title);   
    
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" style="margin-bottom: 0px;">
    <span id='idorden' style="display: none"><?php echo $orden['id']?></span>
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <input id="orden_fecha" name="orden_fecha"  disabled type="text" value="<?php echo $orden['fecha']?>">
                        <label class="active" class="active" for="orden_fecha">Fecha</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field">
                        <input id="orden_fechaapagar" name="orden_fechaapagar" type="text" value="<?php echo $orden['fechapagar']?>">
                        <label class="active" for="orden_fechaapagar">Fecha a pagar</label>                
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="input-field">
                            <input name="proveedor" type="text" id="proveedor_autocomplete" value="<?php echo $orden['proveedor']?>"> 
                            <label class="active" for="proveedor">Proveedor *</label>
                            <input type="hidden" id="idproveedor" value="<?php echo $orden['idproveedor']?>">
                        </div>
                        <p id="orden_proveedor" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <input id="orden_folio" type="text" value="<?php echo $orden['nofactura']?>">
                        <label class="active">Folio *</label>
                    </div>
                     <p id="orden_folio" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>  
                </div>
                <div class="col s6">
                    <div class="input-field">
                        <select name="orden_status" id="orden_status">
                            <option <?php if($orden['status'] == 'pagada') echo ' selected="selected"' ?>value="pagada">Si</option>
                            <option <?php if($orden['status'] == 'no pagada') echo ' selected="selected"' ?>value="no pagada">No</option>
                        </select>
                        <label class="active" for="orden_status" class="active">Pagada</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input name="producto" type="text" id="productos_autocomplete">
                             <label class="active" for="productos">Productos</label>
                            <input type="hidden" id="idproducto">
                        </div>
                    </div>
                    <div class="col s1" style="margin-top: 31px; padding-right: 21px; margin-right: 0px; margin-left: -21px;">
                        <i id="addproduct" style="color: #050661; cursor: pointer"class="small mdi-content-add-box"></i>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>
<p style="color: rgb(158, 158, 158); margin-top: 0px; padding-left: 24px;">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s12">
        <table id="order-items" class="table-inputs bordered ordertable">
            <thead>
                <th>Cantidad</th>
                <th style="width: 480px">Producto</th>
                <th>Caducidad</th>
                <th>Precio costo</th>
                <th>Precio venta</th>
                <th>Subtotal</th>
                <th>Opciones</th>
            </thead>
            <tbody>
                <?php foreach ($orden['orden_items'] as $item) :?>
                <?php //echo'<pre>';var_dump($item); echo '<pre>';?>
                <tr id="<?php echo $item['id']?>">
                    <td id="cantidad"><input type="number" value="<?php echo $item['cantidad']?>" min="1"></td>
                    <td id="producto" style="padding-left: 12px;"><span id="idarticulo" style="display: none"><?php echo $item['idarticulo']?></span><span id="producto_nombre"><?php echo $item['articulo']?></span></td>
                    <td id="caducidad" class="datepicker" style="padding-left: 12px;"><input class="input-datepicker" type="text" value="<?php echo $item['caducidad']?>"></td>
                    <td id="costo"><input type="text" value="<?php echo $item['costo']?>"></td>
                    <td id="costo"><input type="text" value="<?php echo $item['precio']?>"></td>
                    <td id="subtotal" style="padding-left: 12px;"><?php echo $item['importe']?></td>
                    <td id="opciones">
                        <a id="show_item" class="tooltipped modal-trigger" href="#view-modal-articulo-<?php echo $item['idarticulo']?>" data-tooltip="Visualizar" data-position="left"><i class="tiny mdi-image-remove-red-eye"></i></a>
                       <a  id="delete_item" class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='javascript:void(0)'><i class="tiny mdi-action-delete"></i></a>
                    </td>
                </tr>           
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
        <div class="row">
            <div class="col s12 ordertotal-container">
                <p style="font-size: 16px; float: right; padding-right: 24px;">Total: <span id="total">0.00</span>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col s6">
        <fieldset style="position: relative" id="pdf-container">
            <legend>Factura PDF</legend>
            <?php if(is_null($orden['facturapdf'])) :?>
                <div class="file-field input-field">
                    <input class="file-path validate" type="text"/>
                    <div class="btn">
                      <span>PDF</span>
                      <input id="orden_pdf" name="pdf" type="file" accept=".pdf"/>
                    </div>
                </div>
            <?php else :?>
            <?php 
                $facturaPdfExplode = explode('/', $orden['facturapdf']);
            ?>
            <div>
                <img src="/img/compras/pdf_default.png"
                <div style="display: inline"><a target="_blank" href="<?php echo $orden['facturapdf'] ?>"><?php echo $facturaPdfExplode[3]?></a></div>
                <a href="javascript:void(0)" ><i id="remove_factura" class="small mdi-action-delete" style="position: absolute; right: 12px; bottom: 6px; color: #b71c1c;"></i></a>
            </div>
             
            <?php endif;?>
        </fieldset>       
    </div>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button id="save_order" style="width: 100%; height: 45px; margin-top: 15px"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('select').material_select();
        
        //Inicializamos el autocomplete de fecha a pagar
        $('input#orden_fechaapagar').datepicker({
            minDate: 0,
            changeDay: true,
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            monthNamesShort: [ "Ene ", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" ],
   
        });

        var proveedores;
        var productos;
        var delete_items = new Array();
        
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproveedores',
            async: false,
            success: function (data) {
                proveedores = data;
            }
        });
        
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproductos',
            async: false,
            success: function (data) {
                productos = data;
            }
        });
        
        
        $('#proveedor_autocomplete').autocomplete({
            source:proveedores,
            select: function( event, ui ) {
                $('#idproveedor').val(ui.item.value);
                $(this).val(ui.item.label);
                event.preventDefault();
            }
        });
        
        $('#productos_autocomplete').autocomplete({
            source:productos,
            select: function( event, ui ) {
                $('#idproducto').val(ui.item.value);
                $(this).val(ui.item.label);
                event.preventDefault();
            }
        });
        
        //Fomatmoney subtotal
        $.each($('td#subtotal'),function(index,element){
            var new_subtotal = formatMoney(parseFloat($(element).text()),'$');
            $(element).text(new_subtotal);
        });
        updateTotal();
        
        //EVento cantidad
        $('td#cantidad').find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
        
         $('td#cantidad').find('input').on('change',function(){
            //modifcamos el subtotal
            var costo = parseInt($(this).closest('tr').find('#costo input').val());
            var new_subtotal = costo * $(this).val();

            $(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
                updateTotal();

         });
         
        //Evento costo
        $('td#costo').find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});

        $('td#costo').find('input').on('blur',function(){



            var cantidad = $(this).closest('tr').find('#cantidad input').val();
            var new_subtotal = cantidad  * $(this).val();


           $(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
           updateTotal();

        });
        
        //EVento precio
        $('td#precio').find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
        
        
        //evento delete
        $('td#opciones').find('#delete_item').on('click',function(){
            var id_item = $(this).closest('tr').attr('id');
            var modalName = '#delete-modal-item-'+id_item;
             $.get(
                 '/compras/deleteitem',
                 {id: id_item, html:true},
                 function (modal){
                    $('table').after(modal);
                    $(modalName).openModal();
                 }
                 
             );
        
        });
        
        $('input.input-datepicker').on('focus',function(){
            //Cambiamos los estilos;
            $('table.ui-datepicker-calendar').css('display','none');
             var $this = $(this);
              if(!$this.data('datepicker')) {
                 $this.removeClass("hasDatepicker");
                 $(this).datepicker({
                     changeMonth: true,
                     changeYear: true,
                     dateFormat: 'mm/y',
                     defaultDate: '01/01/20',
                     monthNamesShort: [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" ],
                     onClose: function(dateText, inst) { 
                         var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                         var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                         $(this).datepicker('setDate', new Date(year, month, 1));
                         //mantenemos los estilos;
                         $('table.ui-datepicker-calendar').css('display','none');
                     },
                 });
                 $this.datepicker("show");
              }

         });
        
        //Evento show item
        $('a#show_item').on('click',function(){
            var idproduct = $(this).closest('tr').find('span#idarticulo').text();
            var modalName = '#view-modal-articulo-'+idproduct;
            var productName = $(this).closest('tr').find('span#producto_nombre').text();
            $.get('/compras/getarticulobyid',
                 {idarticulovariante:idproduct,product_name:productName},
                 function(modal){
                     $('table').after(modal);
                     $(modalName).openModal();
                 }
            ); 
        });
        
        
        //evento add product
        $('#addproduct').on('click',function(){
            if($('#productos_autocomplete').val() != ''){
                var tr = $('<tr>');
                var td_cantidad = $('<td id="cantidad"><input type="number" min="1" value="1"></td>').appendTo(tr);
                var td_producto = $('<td id="producto" style="padding-left: 12px;"><span id="idarticulo" style="display:none">'+$('input#idproducto').val()+'</span><span id="producto_nombre">'+$('#productos_autocomplete').val()+'</span></td>').appendTo(tr);        
                var td_caducidad = $('<td class="datepicker" id="caducidad" style="padding-left: 12px;"><input class="input-datepicker" type="text"></td>').appendTo(tr);
                var td_costo = $('<td id="costo" ><span style="visibility: hidden"></span><input type="text" value="0.00"></td>').appendTo(tr);
                var td_precio = $('<td id="precio" ><span style="visibility: hidden"></span><input type="text" value="0.00"></td>').appendTo(tr);
                var td_subtotal = $('<td id="subtotal" style="padding-left: 12px;">'+formatMoney(0,'$')+'</td>').appendTo(tr);
                var td_opciones = $('<td><a id="show_item" class="tooltipped modal-trigger" data-position="left" data-tooltip="Visualizar" href="#view-modal-articulo-'+$('#idproducto').val()+'"><i class="tiny mdi-image-remove-red-eye"></i></a>&nbsp;&nbsp;<a id="delete_item" style="margin-left: 4px;" class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href="javascript:void(0)"><i class="tiny mdi-action-delete"></i></a></td>').appendTo(tr);
                
                
                $('tbody').append(tr);
                $('#productos_autocomplete').val('');
                
                //EVento cantidad
                td_cantidad.find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
                
                td_cantidad.find('input').on('change',function(){
                   //modifcamos el subtotal
                   var costo = parseInt($(this).closest('tr').find('#costo input').val());
                   var new_subtotal = costo * $(this).val();
                  
                   $(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
                   updateTotal();
 
                });
                
                //Evento costo
                td_costo.find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
                
                td_costo.find('input').on('blur',function(){
                    
                    
                    
                    var cantidad = $(this).closest('tr').find('#cantidad input').val();
                    var new_subtotal = cantidad  * $(this).val();

                    
                   $(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
                   updateTotal();
                    
                });
                
                //EVento precio
                td_precio.find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
                
                //Evento show item
                $('a#show_item').on('click',function(){
                    var idproduct = $(this).closest('tr').find('span#idarticulo').text();
                    var modalName = '#view-modal-articulo-'+idproduct;
                    var productName = $(this).closest('tr').find('span#producto_nombre').text();
                    $.get('/compras/getarticulobyid',
                         {idarticulovariante:idproduct,product_name:productName},
                         function(modal){
                             $('table').after(modal);
                             $(modalName).openModal();
                         }
                     ); 

                });
                
                $('input.input-datepicker').on('focus',function(){
                    //Cambiamos los estilos;
                    $('table.ui-datepicker-calendar').css('display','none');
                     var $this = $(this);
                      if(!$this.data('datepicker')) {
                         $this.removeClass("hasDatepicker");
                         $(this).datepicker({
                             changeMonth: true,
                             changeYear: true,
                             dateFormat: 'mm/y',
                             defaultDate: '01/01/20',
                             monthNamesShort: [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" ],
                             onClose: function(dateText, inst) { 
                                 var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                                 var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                                 $(this).datepicker('setDate', new Date(year, month, 1));
                                 //mantenemos los estilos;
                                 $('table.ui-datepicker-calendar').css('display','none');
                             },
                         });
                         $this.datepicker("show");
                      }

                 });
                 
                  
            }else{
                alert('No hay productos por agregar');
            }
        });
        
        
        //Evento Save
        $('#save_order').on('click',function(e){
            //Valida los campos requeridos
            var isValid = true;
            
            if($('#proveedor_autocomplete').val() == ''){
                isValid = false;
                $('p#orden_proveedor').show();
            }else{
                $('p#orden_proveedor').hide();
            }
            
            if($('input#orden_folio').val() == ''){
                isValid = false;
                $('p#orden_folio').show();
            }else{
                $('p#orden_folio').hide();
            }
            
            if(isValid){
              //Verificamos que almenos se tenga un item
              var rowCount = $('tbody').children().length;
              
              var orden_facturapdf = null;

                  if($('input[name=pdf]').val() != ''){
                    
                    var inputFile = document.getElementById('orden_pdf');
                    var file = inputFile.files[0];
                    var data = new FormData();
                    data.append('archivo',file);
                    $.ajax({
                        url:'/compras/uploadcomprapdf',
                        type:'POST',
                        contentType:false,
                        data:data,
                        processData:false,
                        cache:false,
                        async: false,
                        success: function (data) {
                            var response = JSON.parse(data);
                            orden_facturapdf = response.compra_facturapdf;
                        }  
                    });
  
                 }
              
              if(rowCount >= 1){
                  //Guardamos la informacion de la orden en un objeto
                  var orden = {
                      orden_facturapdf:orden_facturapdf,
                      idorden: $('#idorden').text(),
                      orden_fecha:$('input#orden_fecha').val(),
                      orden_folio: $('input#orden_folio').val(),
                      orden_proveedor : $('input#idproveedor').val(),
                      orden_status : $('select').val(),
                      orden_importe: $('#total').text(),
                      orden_fechaapagar:$('input#orden_fechaapagar').val(),
                      orden_items : new Array(),
                  }
                  
                  //Hacemos un foreach a nuestros items de la orden
                  $.each($('table.ordertable tbody').children(),function(index,element){

                        var item = {
                            idordendetalle    : $(element).attr('id'),
                            idarticulovariante: $(element).find('span#idarticulo').text(),
                            ordencompradetalle_caducidad : $(element).find('td#caducidad').find('input').val(),
                            ordencompradetalle_cantidad  : $(element).find('td#cantidad').find('input').val(),
                            ordencompradetalle_costo     : $(element).find('td#costo').find('input').val(),
                            ordencompradetalle_precio    : $(element).find('td#precio').find('input').val(),
                            ordencompradetalle_importe   : $(element).find('td#subtotal').text(),
                        }
                        orden.orden_items.push(item);
                    
                  });
                  

                  
                $.post('/compras/editar',
                    {orden:orden},
                    function(response){
                       if(response){
                           window.location.replace("/compras");
                       }
                    }
                );
                  
                  
              }else{
                  alert('Debe tener por lo menos un item en su factura para guardarla');
              }
            }else{
                e.preventDefault();
            }
            
            
        });
        

        function updateTotal(){
           var total = 0;
           $.each($('td#subtotal'),function(index,element){
               
                var subtotalText = $(element).text();
                var split = subtotalText.split('$');
                var subtotal =  split[1];

               subtotal = subtotal.replace(',','');
               total= (parseFloat(total) + parseFloat(subtotal));
               
           });
           
           $('#total').text(formatMoney(total,'$'));
           
       }
       
       function formatMoney(n, currency) {
            return currency + " " + n.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,");
        }
        
        $('#remove_factura').on('click',function(){
            
            var idorden = $('span#idorden').text();
            var modalName = '#delete-modal-facturapdf-'+idorden;
            $.get('/compras/removefacturapdf',
                 {idorden:idorden,html:true},
                 function(modal){
                     $('table').after(modal);
                     $(modalName).openModal();
                 }
            );
            
        });
        
        
    });
    
    
</script>
