<?php
    $title = 'Nueva compra';
    $this->headTitle($title);
    
    //Fecha
    $fecha = new DateTime();
    $fecha = $fecha->format('d/m/Y');
?>
<style>

</style>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row">
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <label>Fecha</label>
                        <input disabled type="text" value="<?php echo $fecha?>">
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field">
                        <select>
                            <option value="pagada">Si</option>
                            <option value="no pagada">No</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="input-field">
                            <label>Proveedor</label>
                            <input type="text" id="proveedor_autocomplete">
                            <input type="hidden" id="idproveedor">
                        </div>
                    </div>
                </div>
            </fieldset>
        </div> 
    </div>
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <label>Folio</label>
                        <input type="text">
                    </div>
                </div>
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <label>Productos</label>
                            <input type="text" id="productos_autocomplete">
                            <input type="hidden" id="idproduct">
                        </div>
                    </div>
                    <div class="col s1" style="padding-top: 21px; cursor: pointer; color: #00086E">
                        <i id="addproduct" class="small mdi-content-add-box"></i>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="col s12">
        <table class="striped">
            <thead>
                <tr>
                    <th>Cantidad</th>
                    <th>Producto</th>
                    <th>Caducidad</th>    
                    <th>Precio costo</th>
                    <th>Precio venta</th>
                    <th>Subtotal</th>
                    <th>Opciones    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>2</td>
                    <td>Electrolit 500ml; sabro fresa;</td>
                    <td>05/2015</td>
                    <td>50.00</td>
                    <td>60.00</td>
                    <td>100.00</td>
                    <td>
                        <a class="tooltipped modal-trigger" data-position="left" data-tooltip="Visualizar" href="<?php echo "#view-modal-articulo-".$producto['id']?>"><i class="tiny mdi-image-remove-red-eye"></i></a>
                        &nbsp;&nbsp;
                        <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-articulo-".$producto['id'] ?>'><i class="tiny mdi-action-delete"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<script>

    $(document).ready(function(){
        $('select').material_select();
        

        var proveedores;
        var productos;
    
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproveedores',
            async: false,
            success: function (data) {
                proveedores = data;
            }
        });
        
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproductos',
            async: false,
            success: function (data) {
                productos = data;
            }
        });
        
        $('#proveedor_autocomplete').autocomplete({
            source:proveedores,
            select: function( event, ui ) {
                $(this).val(ui.item.label);
                $('input#idproveedor').val(ui.item.value);
                event.preventDefault();

            }
        });
        
        $('#productos_autocomplete').autocomplete({
            source:productos,
            select: function( event, ui ) {
                $(this).val(ui.item.label);
                $('input#idproduct').val(ui.item.value);
                event.preventDefault();

            }
        });
        
        $('i#addproduct').on('click',function(){
            if($('#productos_autocomplete').val() != ''){
                
            }else{
                alert('No hay producto para agregar');
            }
        });
        
    });


</script>