<?php
    $title = 'Nueva compra';
    $this->headTitle($title);
    
    //Fecha
    $fecha = new DateTime();
    $fecha = $fecha->format('d/m/Y');
?>
<style>

</style>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row">
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <label>Fecha</label>
                        <input disabled type="text" value="<?php echo $fecha?>">
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field">
                        <select>
                            <option value="pagada">Si</option>
                            <option value="no pagada">No</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="input-field">
                            <label>Proveedor</label>
                            <input type="text" id="proveedor_autocomplete">
                        </div>
                    </div>
                </div>
            </fieldset>
        </div> 
    </div>
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <label>Folio</label>
                        <input type="text">
                    </div>
                </div>
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <label>Productos</label>
                            <input type="text" id="productos_autocomplete">
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>

<script>

    $(document).ready(function(){
        $('select').material_select();
        

        var proveedores;
        var productos;
    
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproveedores',
            async: false,
            success: function (data) {
                proveedores = data;
            }
        });
        
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproductos',
            async: false,
            success: function (data) {
                productos = data;
            }
        });
        
        

        $('#proveedor_autocomplete').autocomplete({
            source:proveedores,
        });
        
        $('#productos_autocomplete').autocomplete({
            source:productos,
        });
        
    });


</script>